site_name: SciCat Documentation
docs_dir: ../../docs


nav: 
  - Home: index.md
  - SciCat User Guide:  
    - user-guide/index.md
    - Login:
      - login/index.md
      - Anonymous: login/Anonymous.md
      - Dashboard: login/Dashboard.md
    - Datasets:
      - datasets/index.md
      - Publishing data: datasets/Publishing.md
      - Publishing data Advanced: datasets/PublishingAdvanced.md
    - Proposals: 
      - proposals/index.md
    - Samples: samples/index.md
    - Instruments: instruments.md
    - Troubleshooting:
      - troubleshoot/index.md
  
  - SciCat Operator Guide: 
    - operator-guide/index.md
    - swagger/index.md
    - backendconfig/index.md
    - backendconfig/authorization/index.md
    - backendconfig/dois.md
    

  - About:
      - about/index.md

theme: material 

plugins:
  - search
  - glightbox
  - section-index


extra_css:
  - custom.css
